apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: high-cpu-utilization-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: high-cpu-utilization-deployment
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70   # target average CPU utilization %

